<!DOCTYPE html>
<body style="font-family:helvetica">
   <hr style="border-top-width:1px;border-top-style:solid;border-top-color:#fa5500">
   <table width="600">
      <div style="line-height:1.6em">
      <p>Datos de contacto:</p>  
      <p>&nbsp;</p>  

      <p>Nombres: <?php echo $this->nombres ?></p>  
      <p>Email: <?php echo $this->email ?></p>  
      <p>Telefono: <?php echo $this->telefono ?></p>  
      <p>Pais: <?php echo $this->pais ?></p>  
      <p>Ciudad: <?php echo $this->ciudad ?></p>  
      <p>Numero de cajas: <?php echo $this->cajas ?></p>  
      
   </table>
</body>
</html>