<?php $date = new \DateTime('NOW'); ?>

<div style="padding: 10px; border: 1px solid #C00">
    <h1 style="color: #C00;"><img src="http://themify.me/wp-content/uploads/2010/11/bug-icon.gif" width="25" heigth="25"/> Application Exception </h1>    
    <?php if (!empty($this->data)) : ?>
        <hr/>
        <h3>Debug : </h3>
        <pre>
            <?php print_r($this->data); ?>
        </pre>
    <?php endif; ?>    
    <hr/>
    <h3>Information : </h3>
    <h3><?php echo get_class($this->exception); ?></h3>
    <dl>
         <?php if (!empty($this->uri)): ?>
            <dt><?php echo 'Uri' ?>:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $this->uri ?></pre>
            </dd>
        <?php endif; ?>
        
        <dt><?php echo 'File' ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
        </dd>
        <dt><?php echo 'Message' ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
        </dd>
        <dt><?php echo 'Stack trace' ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
        </dd>
    </dl>
    <?php
    $e = $this->exception->getPrevious();
    if ($e) :
        ?>
        <hr/>
        <h2>Previous : </h2>
        <ul class="unstyled">
            <?php while ($e) : ?>
                <li>
                    <h3><?php echo get_class($e); ?></h3>
                    <dl>
                        <dt>File :</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                        </dd>
                        <dt>Message :</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                        </dd>
                        <dt>Stack trace :</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php
                $e = $e->getPrevious();
            endwhile;
            ?>
        </ul>
    <?php endif; ?>
    <p><b><?php echo $date->format('Y-m-d h:i:s') ?></b></p>
</div>
