<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Util',
        'Application',
        'Orders'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './common',
            './module',
            './vendor',
            './web',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    )
);
