<div class="mn-container mn-off">
    <div class="mn-colLeft">
        <div class="mn-header">
        </div>
        <h2>By hackers</h2>
        <h3>For hackers</h3>
        <h4>An organic & synthetic beverage</h4>
        <button class="btn_rotar"></button>
        <p>Your either <span>ON</span> or <span>OFF</span>... which is it?</p>
    </div>
    <div class="mn-colRight">
        <span id="girar" class="icon-undo" title="Girar">  </span>
        <span id="volver" class="icon-redo" title="Volver">  </span>
        <div class="mn-botella" id="cont-botella">
            <div class="carta">
                <div class="lado frente"></div>
                <div class="lado atras"></div>	
            </div>
        </div>
        <a style="display:none" id="idOrderSend" href="#" onclick="mn.displayModal(this, 'frmPreOrden', event);" class="mn-preorden">Order Now</a>
    </div>
</div>
<div class="mn-modal" id="frmPreOrden">
    <span id="mnCloseModal" class="mn-close-modal">X</span>
    <form action="" method="post" class="mn-frm-preorden" id="form-mnemonic">
        <h4>Place order</h4>
        <div class="mn-cont-input">
            <input type="text" name="nombres" class="" placeholder="Names">	
        </div>
        <div class="mn-cont-input">
            <input type="text" name="email" class="" placeholder="Email">	
        </div>
        <div class="mn-cont-input">
            <input type="text" name="telefono" class="" placeholder="Phone">	
        </div>
        <div class="mn-cont-input">
            <select name="pais" class="" placeholder="Country">
                <option value="">Country</option>
                <?php foreach($this->countries as $county): ?>
                    <option <?php if($county['co_code'] == $this->country): echo ' selected="selected" '; endif;?> value="<?php echo $county['country_id']; ?>"><?php echo $county['co_name']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="mn-cont-input">
            <input type="text" name="ciudad" class="" placeholder="City">	
        </div>
        <div class="mn-cont-input">
            <input type="text" name="direccion" class="" placeholder="Address">	
        </div>
        <div class="mn-cont-input">
            <select name="cajas" class="" placeholder="Boxes">
                <option value="">Boxes</option>
                <?php for($i=1;$i<=10;$i++): ?>
                    <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <div class="mn-cont-input" style="margin-top: -15px;">
            <label class="label-element">The box contains 6 units</label>	
        </div>
        <div class="mn-cont-input">
            <button class="submit-form" type="submit">Send Order</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    var sw = true, sw1 = true, mn = {};
    $(function () {
        $(".btn_rotar").on('click', function (event) {
            event.preventDefault();
            if (sw == true) {
                $(".mn-container").removeClass('mn-off').addClass('mn-on');
                $("#idOrderSend").css({'display':'block'});
                sw = false;
            } else {
                $(".mn-container").removeClass('mn-on').addClass('mn-off');
                $("#idOrderSend").css({'display':'none'});
                sw = true;
            }
        });
        $("#girar").click(function () {
            $("#cont-botella").addClass('voltear');
            $("#girar").hide();
            $("#volver").show();
        });
        $("#volver").click(function () {
            $("#cont-botella").removeClass('voltear');
            $("#volver").hide();
            $("#girar").show();
        });

        mn.displayModal = function (obj, obj2, e) {
            if (e)
                e.preventDefault();

            var $ob = $(obj), $bd = $('body');

            function hide_modal() {
                $("#" + obj2).hide();
                $bd.removeClass('mn-m');
                $("#mn-hidden-area").remove();
            }
            function show_modal() {
                //$("#mn-hidden-area").attr('display', 'block');
                $("#" + obj2).fadeIn('slow');
                $bd.addClass('mn-m');
            }

            if ($bd.hasClass("mn-m"))
                hide_modal();
            else
                show_modal();
            var hd_hov = $("#mn-hidden-area");
            if (hd_hov.length == 0) {
                var $dv_ = $('<div id="mn-hidden-area" class="mn-hidden-area"></div>');
                $dv_.on("click", function (e) {
                    hide_modal();
                });
                $("#mnCloseModal").on("click", function (e) {
                    hide_modal();
                });
                $("body").append($dv_);
            }
        }

        /*Validacion*/
        $("#form-mnemonic").validate({
            rules: {
                nombres: "required",
                email: {
                    required: true,
                    email: true
                },
                telefono: "required",
                pais: "required",
                direccion: "required",
                cajas: "required"
            },
            messages: {
                nombres: "Please enter your name",
                email: {
                    required: "Please enter your email",
                    email: "Your email is incorrect"
                },
                telefono: "Please enter your phone",
                pais: "Please enter your country",
                direccion: "Please enter your address",
                cajas: "Please enter the number of boxes"
            },
            submitHandler: function (form) {
                
                $.post("/application/index/enviar",
                $('#form-mnemonic').serialize(),
                function(data, status){
                    alert('Your order will register correctly, we will contact you soon.');
                    $("#frmPreOrden").hide();
                    $('body').removeClass('mn-m');
                    $("#mn-hidden-area").remove();
                });
                
            }
        });

    });
</script>